const data = [
{ owner: 
  { name: 'Sublime Text',
    bundleId: 'com.sublimetext.3',
    path: '/Applications/Sublime Text.app',
    processId: 15853 },
 title: 'test.js — to-do list',
 bounds: { height: 1333, x: 0, y: 23, width: 1280 },
 id: 4379,
 memoryUsage: 6829320 },
{ owner: 
  { name: 'Code',
    bundleId: 'com.microsoft.VSCode',
    path: '/Applications/Visual Studio Code.app',
    processId: 34319 },
 title: 'webpack.config.js — productivity-manager',
 bounds: { height: 1201, x: 734, y: 94, width: 1367 },
 id: 4695,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Code',
    bundleId: 'com.microsoft.VSCode',
    path: '/Applications/Visual Studio Code.app',
    processId: 34319 },
 title: 'webpack.config.js — productivity-manager',
 bounds: { height: 1201, x: 734, y: 94, width: 1367 },
 id: 4695,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Code',
    bundleId: 'com.microsoft.VSCode',
    path: '/Applications/Visual Studio Code.app',
    processId: 34319 },
 title: 'webpack.config.js — productivity-manager',
 bounds: { height: 1201, x: 734, y: 94, width: 1367 },
 id: 4695,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: '',
 bounds: { height: 167, x: 1280, y: 96, width: 1280 },
 id: 4712,
 memoryUsage: 857352 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: 'A tale of Webpack 4 and how to finally configure it in the right way',
 bounds: { height: 1333, x: 1280, y: 23, width: 1280 },
 id: 4363,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: 'A tale of Webpack 4 and how to finally configure it in the right way',
 bounds: { height: 1333, x: 877, y: 23, width: 1683 },
 id: 4363,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: 'Firebase',
 bounds: { height: 1333, x: 0, y: 23, width: 2146 },
 id: 3496,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: '',
 bounds: { height: 167, x: 0, y: 96, width: 2146 },
 id: 4713,
 memoryUsage: 1447176 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: 'Inbox - blees.email@gmail.com - Gmail',
 bounds: { height: 1333, x: 0, y: 23, width: 2146 },
 id: 3496,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: 'Bloomberg - Bloomberg',
 bounds: { height: 1333, x: 0, y: 23, width: 2146 },
 id: 3496,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: 'Inbox - blees.email@gmail.com - Gmail',
 bounds: { height: 1333, x: 0, y: 23, width: 2146 },
 id: 3496,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Google Chrome',
    bundleId: 'com.google.Chrome',
    path: '/Applications/Google Chrome.app',
    processId: 460 },
 title: 'Bloomberg - Bloomberg',
 bounds: { height: 1333, x: 0, y: 23, width: 2146 },
 id: 3496,
 memoryUsage: 1128 },
{ owner: 
  { name: 'Sublime Text',
    bundleId: 'com.sublimetext.3',
    path: '/Applications/Sublime Text.app',
    processId: 15853 },
 title: 'webpack.config.js — to-do list',
 bounds: { height: 1333, x: 0, y: 23, width: 1280 },
 id: 4379,
 memoryUsage: 6829320 }
];