export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const PATCH_ACTIVITY = 'PATCH_ACTIVITY';
export const CATEGORIZE_ACTIVITY = 'CATEGORIZE_ACTIVITY';
export const AFFIRM_CATEGORIZATION = 'AFFIRM_CATEGORIZATION';
export const SET_ALL_ACTIVITIES = 'SET_ALL_ACTIVITIES';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const TRACK_APP_TITLE = 'TRACK_APP_TITLE';
export const UNTRACK_APP_TITLE = 'UNTRACK_APP_TITLE';
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const LOG_OUT = 'LOG_OUT';


