export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const PATCH_ACTIVITY = 'PATCH_ACTIVITY';
export const CATEGORIZE_ACTIVITY = 'CATEGORIZE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';


